### ISSUE TITLE
JWM and message threading

### ISSUE THREAD

**Issue by tplooker** [mattrglobal/jwm#11]
The thread id attribute defined in the JWM specification currently hints at the concept of message threading without the specification actually discussing the concept of message threading. Should message threading be discussed explicitly in this specification, if so to what extent? Otherwise should it be removed?

**Comment by kdenhartog** [comment]
This feels like a concern specifically for the protocol layer above. I like the idea of leaving it out of scope here to make it rather simple to understand JWMs. Then as we specify a protocol on top we can add that detail in. Since it's an optional attribute it's possible that someone may want to remove the message threading all together and support something more stateless.

**Comment by tplooker** [comment]
I agree we definitely do not want to complicate at this layer and give the impression that threading is required with all applications of JWMs as it is not

**Comment by kdenhartog** [comment]
Just looking back at this now after a few months since my original response. I think what I said before stands, but it may be useful to define how a "well known" short-hand attribute (such as "thread_id") can be registered so that name collisions won't occur. When I read through the spec, section 3.2 seems to firmly define how this should be handled. I propose that DIDComm would define this following those aspects to define "thread_id". Is that where everyone else is at with this issue?
